import type { MetadataRoute } from "next";
import { contentDatesFor } from "@/lib/content-dates";
import { siteUrl } from "@/lib/shared";
import { source } from "@/lib/source";

// Docs pages get per-page lastModified from git commit dates (generated by
// scripts/generate-content-dates.mjs). BUILD_TIME stamps the homepage and is
// the fallback when git history is unavailable at build time. Set BUILD_TIME
// in CI (e.g. `export BUILD_TIME=$(date -u +%FT%TZ)`) for a per-deploy
// timestamp; without it, fall back to process start, which is stable within
// the process lifetime — better than `new Date()` per call (which crawlers
// read as "everything changed today" and erodes trust).
const BUILD_TIME = process.env.BUILD_TIME
  ? new Date(process.env.BUILD_TIME)
  : new Date();

const GET_STARTED_PREFIXES = [
  "/docs/installation",
  "/docs/first-install",
  "/docs/project-setup",
  "/docs/migrating",
  "/docs/registries",
  "/docs/commands",
];

function priorityFor(url: string): number {
  if (GET_STARTED_PREFIXES.some((p) => url === p || url.startsWith(`${p}/`))) {
    return 0.9;
  }
  const segments = url.replace(/^\//, "").split("/").filter(Boolean);
  if (segments.length <= 2) return 0.8;
  return 0.7;
}

export default function sitemap(): MetadataRoute.Sitemap {
  const homeRoute: MetadataRoute.Sitemap[number] = {
    url: siteUrl,
    lastModified: BUILD_TIME,
    changeFrequency: "weekly",
    priority: 1,
  };

  const docRoutes: MetadataRoute.Sitemap = source.getPages().map((page) => {
    const { modified } = contentDatesFor(page.path);

    return {
      url: `${siteUrl}${page.url}`,
      lastModified: modified ? new Date(modified) : BUILD_TIME,
      changeFrequency: "weekly" as const,
      priority: priorityFor(page.url),
    };
  });

  return [homeRoute, ...docRoutes];
}
