import generated from "@/lib/generated/content-dates.json";

type ContentDates = {
  published?: string;
  modified?: string;
};

const contentDates: Record<string, ContentDates> = generated;

/**
 * Git commit dates for a docs page, keyed by its file path under
 * `content/docs` (e.g. `packages/install.mdx`). The committed map is
 * regenerated by `scripts/generate-content-dates.mjs` whenever a full clone
 * is available; deploy containers without usable git history build from the
 * committed snapshot. Pages missing from the map yield empty entries, so
 * both fields are optional.
 */
export function contentDatesFor(filePath: string): ContentDates {
  return contentDates[filePath] ?? {};
}
